//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ics.lu.se", ConfigurationName="ERPServiceReference.WebApplicationSoap")]
    public interface WebApplicationSoap
    {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://ics.lu.se is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/HelloWorld", ReplyAction="*")]
        ERPServiceReference.HelloWorldResponse HelloWorld(ERPServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPServiceReference.HelloWorldResponse> HelloWorldAsync(ERPServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name HelloSoapResult from namespace http://ics.lu.se is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/HelloSoap", ReplyAction="*")]
        ERPServiceReference.HelloSoapResponse HelloSoap(ERPServiceReference.HelloSoapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ics.lu.se/HelloSoap", ReplyAction="*")]
        System.Threading.Tasks.Task<ERPServiceReference.HelloSoapResponse> HelloSoapAsync(ERPServiceReference.HelloSoapRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://ics.lu.se", Order=0)]
        public ERPServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(ERPServiceReference.HelloWorldRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody
    {
        
        public HelloWorldRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://ics.lu.se", Order=0)]
        public ERPServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(ERPServiceReference.HelloWorldResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se")]
    public partial class HelloWorldResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody()
        {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult)
        {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloSoapRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloSoap", Namespace="http://ics.lu.se", Order=0)]
        public ERPServiceReference.HelloSoapRequestBody Body;
        
        public HelloSoapRequest()
        {
        }
        
        public HelloSoapRequest(ERPServiceReference.HelloSoapRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloSoapRequestBody
    {
        
        public HelloSoapRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloSoapResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloSoapResponse", Namespace="http://ics.lu.se", Order=0)]
        public ERPServiceReference.HelloSoapResponseBody Body;
        
        public HelloSoapResponse()
        {
        }
        
        public HelloSoapResponse(ERPServiceReference.HelloSoapResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ics.lu.se")]
    public partial class HelloSoapResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloSoapResult;
        
        public HelloSoapResponseBody()
        {
        }
        
        public HelloSoapResponseBody(string HelloSoapResult)
        {
            this.HelloSoapResult = HelloSoapResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface WebApplicationSoapChannel : ERPServiceReference.WebApplicationSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class WebApplicationSoapClient : System.ServiceModel.ClientBase<ERPServiceReference.WebApplicationSoap>, ERPServiceReference.WebApplicationSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebApplicationSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WebApplicationSoapClient.GetBindingForEndpoint(endpointConfiguration), WebApplicationSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebApplicationSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebApplicationSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebApplicationSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebApplicationSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebApplicationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPServiceReference.HelloWorldResponse ERPServiceReference.WebApplicationSoap.HelloWorld(ERPServiceReference.HelloWorldRequest request)
        {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld()
        {
            ERPServiceReference.HelloWorldRequest inValue = new ERPServiceReference.HelloWorldRequest();
            inValue.Body = new ERPServiceReference.HelloWorldRequestBody();
            ERPServiceReference.HelloWorldResponse retVal = ((ERPServiceReference.WebApplicationSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPServiceReference.HelloWorldResponse> ERPServiceReference.WebApplicationSoap.HelloWorldAsync(ERPServiceReference.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPServiceReference.HelloWorldResponse> HelloWorldAsync()
        {
            ERPServiceReference.HelloWorldRequest inValue = new ERPServiceReference.HelloWorldRequest();
            inValue.Body = new ERPServiceReference.HelloWorldRequestBody();
            return ((ERPServiceReference.WebApplicationSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ERPServiceReference.HelloSoapResponse ERPServiceReference.WebApplicationSoap.HelloSoap(ERPServiceReference.HelloSoapRequest request)
        {
            return base.Channel.HelloSoap(request);
        }
        
        public string HelloSoap()
        {
            ERPServiceReference.HelloSoapRequest inValue = new ERPServiceReference.HelloSoapRequest();
            inValue.Body = new ERPServiceReference.HelloSoapRequestBody();
            ERPServiceReference.HelloSoapResponse retVal = ((ERPServiceReference.WebApplicationSoap)(this)).HelloSoap(inValue);
            return retVal.Body.HelloSoapResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ERPServiceReference.HelloSoapResponse> ERPServiceReference.WebApplicationSoap.HelloSoapAsync(ERPServiceReference.HelloSoapRequest request)
        {
            return base.Channel.HelloSoapAsync(request);
        }
        
        public System.Threading.Tasks.Task<ERPServiceReference.HelloSoapResponse> HelloSoapAsync()
        {
            ERPServiceReference.HelloSoapRequest inValue = new ERPServiceReference.HelloSoapRequest();
            inValue.Body = new ERPServiceReference.HelloSoapRequestBody();
            return ((ERPServiceReference.WebApplicationSoap)(this)).HelloSoapAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebApplicationSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WebApplicationSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebApplicationSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/ERPWEB/WebApplication.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WebApplicationSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost/ERPWEB/WebApplication.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WebApplicationSoap,
            
            WebApplicationSoap12,
        }
    }
}
